version: '3'
services:
  backend:
    image: varun891452/my-backend:latest
    ports:
      - "8000:8000"

  frontend:
    image: varun891452/my-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    
